name: Add Updated to README

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
    contents: write

jobs:
  update-by-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add updated to README
        run: echo "\n\n${{ github.actor }}"  >> README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
